### ISSUE TITLE
Switch experiments to Goblin Dataset

### ISSUE THREAD

**Issue by jensdietrich** [nkiru-ede/MavenNetworkStudy#22]
For background, see: 
1. Jamie et al: Goblin: A Framework for Enriching and Querying the Maven Central Dependency Graph. https://dl.acm.org/doi/10.1145/3643991.3644879 
2. https://2025.msrconf.org/track/msr-2025-mining-challenge 

##  Tasks
1. [ ] Recreate GAV Graph, report |V| and |E|
2. [ ] Recreate GA Graph, report |V| and |E|
3. [ ] Recreate G Graph, report |V| and |E|
4. [ ] Rerun SCC Analysis
5. [ ] Rerun Transitive Closure Analysis
6. [ ] Recomute gini / Lorentz curves
7. [ ]  Rerun analysis of elites (Top-100, Top-200, Top-500) , incl patterns for decline

**Comment by nkiru-ede** [comment]
@jensdietrich I was able to extract a dependency relationship dataset in the below format: 
[first_10_records.csv](https://github.com/user-attachments/files/17270861/first_10_records.csv)
This dataset is above 18GB, however I struggled to see timestamps and tried to scrape the timestamps from maven central, this process took so much time and was not finding a big number of the artifacts so I ended the process.

I have just seen a part of the dump that contains timestamps and I am currently trying to convert the data. It is taking time, I guess because of the size.

I wanted to provide an update on how far I have gone with the data. Will provide another update by COB Tuesday.

![image](https://github.com/user-attachments/assets/6028d616-fa03-442c-ac53-9fcc71dea11c)

**Comment by jensdietrich** [comment]
thanks @Nkiru, noted . Is there perhaps a schema that describes the structure of the dataset?

**Comment by jensdietrich** [comment]
@nkiru-ede  also, you will need to break uo relationshipDetails into columns. Is the target version always a version, or can it be a version constraint (for instance, also could be a range) ?

**Comment by jensdietrich** [comment]
@nkiru-ede  answering my own question -- the zenodo dump has a metamodel (=schema), there is a pdf in https://zenodo.org/records/13734581, here: https://zenodo.org/records/13734581/files/metamodel.pdf . This shows timestamps, you just need to define a cypher queries to extract those.   CC @ulizue

**Comment by nkiru-ede** [comment]
@jensdietrich, thanks for sharing. Yes, I saw the timestamp info, which was why I pasted the below earlier. I have extracted the new data, which is about 50GB, and I am now cleaning the data.

![image](https://github.com/user-attachments/assets/83c068f8-cfeb-4a53-946c-af859ec8cd43)

**Comment by jensdietrich** [comment]
thanks @nkiru-ede  -- looking forward to see how this is going. I suggest to do as much as possible of the analysis with CYPHER queries, this gives it a nice declarative touch. Note the meeting invite for tomorrow, I think you haven't accepted it yet.

**Comment by nkiru-ede** [comment]
@jensdietrich I have accepted the invite. The dataset has 119,660,406 records(edges(GAV)) and the release dates/timestamps belong to the dependencies. I have tried to match the dependencies to artifacts and there are only 175300 matches. 

Will talk about these in the meeting today.

**Comment by nkiru-ede** [comment]
@jensdietrich 

You can find the cypher queries converting the data into links_all and release_all here [cypher queries](https://github.com/nkiru-ede/MavenNetworkStudy/blob/ff1f40804fd453102e6caa1d6233f4471709fd5a/CypherCodes.txt)

The dataset contains 119,660,406 edges/relationships 
[links_all](https://drive.google.com/file/d/1YLHUAi08Y6TGGt9DVbPIiowpJYY2zDhf/view?usp=sharing)
[release_all](https://drive.google.com/file/d/1Bd7EgVE0kVfQfqoEsAdgYxfzevc2LAtO/view?usp=sharing)

After merging the links_all with the release_all, 9 gavs in the source column are without release dates, while 5,104,196 in the target column are without release dates.
[merged data](https://drive.google.com/file/d/109SKGiMLLiCwVWqQTZGs2sU6jTmPyVyJ/view?usp=sharing)

There is no use of dependency range in any of the source artifacts, however, the target artifacts has 813,343 gavs with dependency ranges. I have extracted this into a separate csv - 
[filtered_version_ranges.zip](https://github.com/user-attachments/files/17321690/filtered_version_ranges.zip)


How I intend to handle the missing/odd data:

1. Target release date (dependency range)  -  update the 813,343 with the versions of the source
2. Scrape Maven central for release dates of other missing gavs
3. Remove the rows/records of gavs still unresolved(without release dates). 
4. continue analysis with final dataset

What do you think about the approach?

**Comment by jensdietrich** [comment]
@nkiru-ede  "while 5,104,196 in the target column are without release dates." (I guess you mean that the join with the GAV info cannot be resolved here) vs " the target artifacts has 813,343 gavs with dependency ranges". Note the wording here: there is no such thing as "813,343 gavs with dependency ranges" -- this is basically a "set of GAVs". So if you want to "update the 813,343 with the versions of the source" you need to pick one (or all) from this set. This is easy for one particular pattern ("[<version>]") but tricky otherwise, and will lead to too many edges that interfere with the stats.

I think it would be ok to document that for <3% of edges the target cannot be resolved, quickly study the reasons, and then ignore them. There must be reasons other then dependency ranges  (they explain only approx 20%), so what are they ? I have an idea, but it would be good if you do some data sampling and find out independently. 

cc @ulizue

**Comment by nkiru-ede** [comment]
@jensdietrich 

the 813,343 targets with dependency ranges are without release dates. I have looked at the other 4m+ to see if there is a pattern such as -if target release dates are missing for specific source versions, if target release is null where source release is null. But I could not see any pattern. 

I have removed those rows from the final dataset and we are left with 114,556,210 edges. 

I have started replicating the experiments with the new dataset and updating the charts and tables in a folder 'newData' in the latex document.

**Comment by nkiru-ede** [comment]
@jensdietrich this is the regular expression pattern i used to extract dependency ranges - 
<img width="240" alt="image" src="https://github.com/user-attachments/assets/bdd04614-0dd3-4a40-aa5b-d05c9943d2c6">

**Comment by nkiru-ede** [comment]
@jensdietrich I have uploaded the latest plots on overleaf - will discuss this further in the meeting.

Some highlights:
Below is the innovation chart - note: out of the 14,459,139 Gavs, there aare 206,485 with unusual version formats
![innovationGA](https://github.com/user-attachments/assets/f931ae79-6dad-410e-a77e-0d8fb34152e3)

Below plots show the ratio of first GA to Last GA:
![First-Last-GA-ratio](https://github.com/user-attachments/assets/f187f520-52f4-47e7-ab16-feb5447a6fa5)
![First-Last-GA-ratio-minus2years](https://github.com/user-attachments/assets/66188513-d453-4912-956c-8665bee57281)
in 2004, the ratio is 2.0, meaning there were twice as many new GAs introduced (6) compared to the GAs that were last seen (3)
In 2018, with a ratio of about 1.23, the counts of new (47,334) and retired (38,365) GAs are close, suggesting a balanced churn between new and outgoing GAs
In 2023, with a ratio of 0.88, more GAs were last seen (76,540) than first introduced (67,690), which could imply that more GAs are reaching end-of-life or are becoming obsolete in that year
Higher ratios in early years (e.g., 2002 to 2010) imply rapid growth in the addition of new GAs, with more entering than exiting.
Ratio decrease can be seen between 2023 to 2024, but we already discussed why this is the case and hence why the last 3 years are removed from the last GA plot.

**Comment by jensdietrich** [comment]
Why does the Innovation Maor Version Curve only start in 2005 ?

**Comment by jensdietrich** [comment]
Fix label in first-to-last (it is the reverse atm)

**Comment by jensdietrich** [comment]
Discussed today: 
- [ ] add ratio purple / red to innovation chart
- [ ] analyse top-N (top100, top500, make easy to configure) ratio of replacement for any given year chart. Example datapoint: 20 in 2010 for top100:   in 2010, there were 20 GAs in the Top100 not in the Top100 in the previous year 2009. The datapoint 20 refers to the percentage (20 as 20% of 100)

**Comment by nkiru-ede** [comment]
@jensdietrich 
Major release to Last GA:
![MajorReleaseToLastGA](https://github.com/user-attachments/assets/ec30fbee-8c6a-481b-9836-c0d01660a57d)
There are 141,214 GAs with single version releases. I plotted these events after removing these GAs and the pattern overall seem consistent with before except for the beginning of lastGA.
![Uploading innovationGA_minusSingleGAs.png…]()
And effect can be seen in the below innovation charts:
![MajorReleaseToLastGA_minusSingleGAs](https://github.com/user-attachments/assets/d1d8b1d0-1a8e-4f43-ab03-382be3b2967e)

Ratio of replacement:
![FractionOfReplacement](https://github.com/user-attachments/assets/66dace4e-ce7a-4bac-8900-4025e5271f14)
and this is computed thus:
Len(new_GA)/len(current_top_N(10,100,500)) * 100
where new_GA is the GAs in current topN that are not in previous topN
<img width="133" alt="image" src="https://github.com/user-attachments/assets/cf7c6ee8-1ff9-45a8-a269-117bb825b8b6">
<img width="126" alt="image" src="https://github.com/user-attachments/assets/f3a668a1-792b-42ca-9348-163bfeba0389">
<img width="143" alt="image" src="https://github.com/user-attachments/assets/0dd9bb32-b530-4983-b16f-1de31c741811">
<img width="121" alt="image" src="https://github.com/user-attachments/assets/7cd5f4d9-da7c-4f2b-b169-ed03e9baf897">
<img width="136" alt="image" src="https://github.com/user-attachments/assets/2f3dc7b2-0808-4043-a011-9803fb92810e">
<img width="134" alt="image" src="https://github.com/user-attachments/assets/2e09c6ad-8cf1-4522-aafb-ab32221b0990">
<img width="114" alt="image" src="https://github.com/user-attachments/assets/d859f92c-82ba-43ee-8deb-75f3157eb44e">
<img width="110" alt="image" src="https://github.com/user-attachments/assets/d6d3749d-c8f8-4d47-9d13-ffeb9980a45e">
